# Generated by Django 6.0.6 on 2026-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='override_calculations',
            field=models.BooleanField(default=False, help_text='If checked, automatic salary computation is skipped and deductions can be set manually.'),
        ),
    ]
