# Generated by Django 6.0.6 on 2026-06-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrecord_override_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='employee_link',
            field=models.ForeignKey(blank=True, help_text='Link to the Employee record for auto-filling name and ID.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='payroll.employee'),
        ),
    ]
