# Generated by Django 6.0.6 on 2026-06-26 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollrecord_employee_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_employee_rate', models.DecimalField(decimal_places=4, default='0.0500', max_digits=6)),
                ('sss_monthly_min', models.DecimalField(decimal_places=2, default='5000.00', max_digits=10)),
                ('sss_monthly_max', models.DecimalField(decimal_places=2, default='35000.00', max_digits=10)),
                ('philhealth_employee_rate', models.DecimalField(decimal_places=4, default='0.0250', max_digits=6)),
                ('philhealth_monthly_min', models.DecimalField(decimal_places=2, default='10000.00', max_digits=10)),
                ('philhealth_monthly_max', models.DecimalField(decimal_places=2, default='100000.00', max_digits=10)),
                ('pagibig_monthly_max', models.DecimalField(decimal_places=2, default='10000.00', max_digits=10)),
                ('pagibig_low_rate', models.DecimalField(decimal_places=4, default='0.0100', max_digits=6)),
                ('pagibig_standard_rate', models.DecimalField(decimal_places=4, default='0.0200', max_digits=6)),
                ('pagibig_low_rate_limit', models.DecimalField(decimal_places=2, default='1500.00', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deduction Configuration',
            },
        ),
    ]
