# Generated by Django 6.0.6 on 2026-06-24 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_department_alter_payrollitem_net_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-cutoff_end', 'employee_id', 'employee_name']},
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='cutoff_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='cutoff_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pagibig_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='philhealth_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='sss_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='taxable_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_cutoff_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='withholding_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
