# Generated by Django 6.0.6 on 2026-06-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_backfill_payrollrecord_computations'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
